quarkus.datasource.db-kind=mysql
quarkus.datasource.username=emna
quarkus.datasource.password=emna
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/carvault
quarkus.hibernate-orm.database.generation=update
database.genelickey.location=../jwt/publicKey.pem